# Generated by Django 4.1.1 on 2022-09-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("save", models.BooleanField(default=False, verbose_name="Save")),
                ("read", models.BooleanField(default=False, verbose_name="Read")),
                ("update", models.BooleanField(default=False, verbose_name="Update")),
                ("delete", models.BooleanField(default=False, verbose_name="Delete")),
                (
                    "departmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Permissions",
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="AdminUser",
        ),
        migrations.DeleteModel(
            name="FinanceUser",
        ),
        migrations.DeleteModel(
            name="PurchasingUser",
        ),
        migrations.DeleteModel(
            name="SalesUser",
        ),
    ]
