# Generated by Django 4.1.1 on 2022-09-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0003_alter_permission_delete_alter_permission_read_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="delete",
            field=models.BooleanField(default=False, verbose_name="Delete"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="save",
            field=models.BooleanField(default=False, verbose_name="Save"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="update",
            field=models.BooleanField(default=False, verbose_name="Update"),
        ),
    ]
