# Generated by Django 4.1.1 on 2022-09-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_alter_permission_delete_alter_permission_read_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={},
        ),
    ]
