# Generated by Django 4.1.1 on 2022-09-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_permissions"),
        ("permissions", "0005_alter_permission_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="delete",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="read",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="save",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="update",
        ),
        migrations.AddField(
            model_name="permission",
            name="permissions",
            field=models.CharField(
                choices=[
                    ("s", "Save"),
                    ("r", "Read"),
                    ("u", "Update"),
                    ("d", "Delete"),
                ],
                default=1,
                max_length=1,
                verbose_name="Permissions",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="productid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
    ]
