# Generated by Django 4.1.1 on 2022-09-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=25, verbose_name="Department Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Departments",
                "abstract": False,
            },
        ),
    ]
