# Generated by Django 4.1.1 on 2022-09-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                (
                    "email",
                    models.EmailField(max_length=20, unique=True, verbose_name="Email"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="Password")),
                ("name", models.CharField(max_length=40, verbose_name="Name")),
                (
                    "last_name",
                    models.CharField(max_length=40, verbose_name="Last Name"),
                ),
                (
                    "department",
                    models.CharField(max_length=15, verbose_name="Department"),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
                "abstract": False,
            },
        ),
    ]
